name: Cypress E2E Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        env:
          BRANCH: ${{github.event.pull_request.head.ref}}
        with:
          working-directory: cypress
          browser: chrome
          wait-on: "https://${BRANCH}--aem-boilerplate-commerce--hlxsites.aem.page/"
          config: baseUrl="https://${BRANCH}--aem-boilerplate-commerce--hlxsites.aem.page/"
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore